package com.synq.backend.domain.meeting.entity;

import com.synq.backend.global.entity.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Duration;
import java.time.LocalDateTime;

// 호스트는 별도 FK가 아니라 MeetingParticipant.role=HOST 로 판별한다 (멀티 참여자 모델 지원).
@Entity
@Table(name = "meeting")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Meeting extends BaseEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(name = "project_id", nullable = false)
	private Long projectId;

	@Column(nullable = false)
	private String title;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	private MeetingStatus status;

	@Column(name = "started_at")
	private LocalDateTime startedAt;

	@Column(name = "ended_at")
	private LocalDateTime endedAt;

	// true면 생성 시 부여된 임시 제목을 아직 사용자가 수정하지 않은 상태다.
	// 사용자가 제목을 직접 수정하면 false로 전환되고, 이후 AI 자동 제목 생성 등 다른 로직이
	// 이 값을 덮어쓰지 않아야 한다.
	@Column(name = "title_auto_generated", nullable = false)
	private boolean titleAutoGenerated;

	// non-null이면 현재 일시정지 상태다.
	@Column(name = "paused_at")
	private LocalDateTime pausedAt;

	// 일시정지 중이 아닐 때, 지금까지 계속 흐르고 있는 활성 구간의 시작 시각.
	@Column(name = "last_resumed_at", nullable = false)
	private LocalDateTime lastResumedAt;

	// 마지막 정지/재개 전환 시점까지 누적된 활성 시간(초). activeSeconds() 계산의 기준값.
	@Column(name = "active_seconds_snapshot", nullable = false)
	private long activeSecondsSnapshot;

	private Meeting(Long projectId, String title, MeetingStatus status, LocalDateTime startedAt) {
		this.projectId = projectId;
		this.title = title;
		this.status = status;
		this.startedAt = startedAt;
		this.titleAutoGenerated = true;
		this.lastResumedAt = startedAt;
	}

	// 별도 "녹음 시작" API 없이 생성과 동시에 녹음이 시작된다.
	public static Meeting of(Long projectId, String title) {
		return new Meeting(projectId, title, MeetingStatus.IN_PROGRESS, LocalDateTime.now());
	}

	// 종료 호출 시 즉시 SUMMARIZING 으로 전환하고 종료 시각을 기록한다.
	// 이후 AI 정리 결과에 따라 markSummarized/markSummaryFailed 로 상태가 확정된다.
	public void end() {
		this.status = MeetingStatus.SUMMARIZING;
		this.endedAt = LocalDateTime.now();
	}

	public void markSummarized() {
		this.status = MeetingStatus.SUMMARIZED;
	}

	public void markSummaryFailed() {
		this.status = MeetingStatus.SUMMARY_FAILED;
	}

	public void updateTitle(String title) {
		this.title = title;
		this.titleAutoGenerated = false;
	}

	public void pause() {
		LocalDateTime now = LocalDateTime.now();
		this.activeSecondsSnapshot += Duration.between(lastResumedAt, now).toSeconds();
		this.pausedAt = now;
	}

	public void resume() {
		this.pausedAt = null;
		this.lastResumedAt = LocalDateTime.now();
	}

	public boolean isPaused() {
		return pausedAt != null;
	}

	// 일시정지 구간을 제외한, 회의 시작 이후 누적 활성 시간(초).
	public long activeSeconds() {
		if (isPaused()) {
			return activeSecondsSnapshot;
		}
		return activeSecondsSnapshot + Duration.between(lastResumedAt, LocalDateTime.now()).toSeconds();
	}
}
