package com.synq.backend.domain.meeting.dto;

import com.synq.backend.domain.meeting.entity.Meeting;

public record MeetingTitleUpdateResponse(
		Long meetingId,
		String title,
		boolean userModified
) {
	public static MeetingTitleUpdateResponse from(Meeting meeting) {
		return new MeetingTitleUpdateResponse(
				meeting.getId(),
				meeting.getTitle(),
				!meeting.isTitleAutoGenerated()
		);
	}
}
