package com.synq.backend.domain.meeting.repository;

import com.synq.backend.domain.meeting.entity.Meeting;
import com.synq.backend.domain.meeting.entity.MeetingStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface MeetingRepository extends JpaRepository<Meeting, Long> {

	boolean existsByProjectIdAndStatus(Long projectId, MeetingStatus status);

	List<Meeting> findByProjectIdOrderByCreatedAtDesc(Long projectId);

	// 프로젝트당 IN_PROGRESS 회의는 최대 1개라는 불변식을 서비스 레벨에서만 강제하고 있어,
	// 목록 조회에서도 방어적으로 여러 건일 가능성을 열어두고 호출부에서 최신 것만 취한다.
	List<Meeting> findByProjectIdInAndStatus(List<Long> projectIds, MeetingStatus status);

	List<Meeting> findByStatus(MeetingStatus status);

	@Modifying(flushAutomatically = true, clearAutomatically = true)
	@Query("""
			UPDATE Meeting meeting
			SET meeting.title = :title,
			    meeting.updatedAt = CURRENT_TIMESTAMP
			WHERE meeting.id = :meetingId
			  AND meeting.titleAutoGenerated = true
			""")
	int updateTitleIfAutoGenerated(
			@Param("meetingId") Long meetingId,
			@Param("title") String title
	);

	@Query("""
			SELECT meeting
			FROM Meeting meeting
			WHERE meeting.projectId IN :projectIds
			  AND meeting.startedAt = (
				  SELECT MAX(candidate.startedAt)
				  FROM Meeting candidate
				  WHERE candidate.projectId = meeting.projectId
			  )
			""")
	List<Meeting> findRecentMeetingsByProjectIds(@Param("projectIds") List<Long> projectIds);

	// 정상 /end 와 진행자 연결 끊김에 의한 강제 종료가 동시에 들어와도 한쪽만 반영되도록,
	// 상태 확인과 전환을 하나의 원자적 UPDATE 로 묶는다. 갱신된 row 수가 0이면 이미 종료된 것이다.
	@Modifying(flushAutomatically = true, clearAutomatically = true)
	@Query("""
			UPDATE Meeting meeting
			SET meeting.status = com.synq.backend.domain.meeting.entity.MeetingStatus.SUMMARIZING,
			    meeting.endedAt = CURRENT_TIMESTAMP
			WHERE meeting.id = :meetingId
			  AND meeting.status = com.synq.backend.domain.meeting.entity.MeetingStatus.IN_PROGRESS
			""")
	int endIfInProgress(@Param("meetingId") Long meetingId);
}
