package com.synq.backend.domain.meeting.repository;

import com.synq.backend.domain.meeting.entity.Meeting;
import com.synq.backend.domain.meeting.entity.MeetingStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface MeetingRepository extends JpaRepository<Meeting, Long> {

	boolean existsByProjectIdAndStatus(Long projectId, MeetingStatus status);

	List<Meeting> findByProjectIdOrderByCreatedAtDesc(Long projectId);

	// 프로젝트당 IN_PROGRESS 회의는 최대 1개라는 불변식을 서비스 레벨에서만 강제하고 있어,
	// 목록 조회에서도 방어적으로 여러 건일 가능성을 열어두고 호출부에서 최신 것만 취한다.
	List<Meeting> findByProjectIdInAndStatus(List<Long> projectIds, MeetingStatus status);

	List<Meeting> findByStatus(MeetingStatus status);

	@Modifying(flushAutomatically = true, clearAutomatically = true)
	@Query("""
			UPDATE Meeting meeting
			SET meeting.title = :title,
			    meeting.updatedAt = CURRENT_TIMESTAMP
			WHERE meeting.id = :meetingId
			  AND meeting.titleAutoGenerated = true
			""")
	int updateTitleIfAutoGenerated(
			@Param("meetingId") Long meetingId,
			@Param("title") String title
	);

	@Query("""
			SELECT meeting
			FROM Meeting meeting
			WHERE meeting.projectId IN :projectIds
			  AND meeting.startedAt = (
				  SELECT MAX(candidate.startedAt)
				  FROM Meeting candidate
				  WHERE candidate.projectId = meeting.projectId
			  )
			""")
	List<Meeting> findRecentMeetingsByProjectIds(@Param("projectIds") List<Long> projectIds);
}
