package com.synq.backend.domain.meeting.adapter;

import com.synq.backend.domain.ai.summary.domain.MeetingTitleReader;
import com.synq.backend.domain.ai.summary.domain.MeetingTitleWriter;
import com.synq.backend.domain.meeting.repository.MeetingRepository;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * ai.summary 도메인의 MeetingTitleReader 포트를 meeting 도메인이 구현한 어댑터.
 */
@Component
@RequiredArgsConstructor
public class MeetingTitleReaderAdapter implements MeetingTitleReader, MeetingTitleWriter {

	private final MeetingRepository meetingRepository;

	@Override
	public Optional<String> findTitle(Long meetingId) {
		return meetingRepository.findById(meetingId).map(meeting -> meeting.getTitle());
	}

	@Override
	public boolean updateTitleIfAutoGenerated(Long meetingId, String title) {
		return meetingRepository.updateTitleIfAutoGenerated(meetingId, title) > 0;
	}
}
